development:
  sessions:
      default:
       hosts:
        - datastore2:27017
       password: password
       username: alloysecrets
       database: alloysecrets

production:
  sessions:
      default:
        hosts:
          - datastore2:27017
        database: alloysecrets
        username: alloysecrets
        password: password
